language: go

go:
    - 1.8

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install nodejs
    - npm install

install:
    - go get -u github.com/gopherjs/gopherjs

script:
    - diff -u <(echo -n) <(gofmt -d ./)
    - gopherjs test github.com/flimzy/go-sql.js/bindings github.com/flimzy/go-sql.js/tests
